### ISSUE TITLE
Error: Cannot find module './xstate-test'  

### ISSUE THREAD

**Issue by vehas** [rjdestigter/xstate-marionettist#8]
Error: Cannot find module './xstate-test' from '/node_modules/xstate-marionettist-cypress/dist'
when I try to run 'xstate-marionettist-cypress'
with  import { create } from 'xstate-marionettist-cypress'

**Comment by rjdestigter** [comment]
Looks like I had the wrong configuration for `files` in _package.json_. Should be fixed in _xstate-marionettist-cypress@0.5.1_

**Comment by vehas** [comment]
@0.5.1 working great, thank you for your fast respond
